global:
  resolve_timeout: 5m

templates:
  - "templates/wechat.tmpl"

route:
  group_by: ['one']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'one_wx'
receivers:
- name: 'one_wx'
  wechat_configs:
  - send_resolved: true
    to_party: 22 
    agent_id: '1000023' 
    corp_id: 'wwf1d319ac893985e6'
    api_secret: 'EE15UQ9CJ9A5VjH4eT-bUIbVSMPicJPf5tgQCIguSN4'
# inhibit_rules:
#   - source_match:
#       severity: 'critical'
#     target_match:
#       severity: 'warning'
#     equal: ['alertname', 'dev', 'instance']

