groups:
# client - base
- name: client
  rules:
  - alert: ClientHealthWaring
    expr: up == 0
    for: 5m
    labels:
      severity: page
    annotations:
      summary: "Client status alerts"
      description: "Job {{ $labels.job }} has been down for more than 5 minutes. (current value: {{ $value }} | 1: up, 0: down)"
# host
- name: host
  rules:
  - alert: hostCpuUsageAlert
    expr: sum(avg without (cpu)(irate(node_cpu_seconds_total{mode!='idle'}[5m]))) by (instance) > 0.80
    for: 30m
    labels:
      severity: page
    annotations:
      summary: "Instance CPU Usage High"
      description: "CPU usage above 80% (current value: {{ $value }})"
  - alert: hostDiskUsageAlert
    expr: 100 - ((node_filesystem_avail_bytes{fstype=~"ext4|xfs"} * 100) / node_filesystem_size_bytes {fstype=~"ext4|xfs"}) > 80
    for: 1h
    labels:
      serverity: page
    annotations:
      summary: "Instance Disk Usage High"
      description: "Disk usage above 80% (current value: '{{ $labels.mountpoint }}' : {{ $value }})"
  - alert: hostMemoryUsageAlert
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes > 0.80
    for: 30m
    labels:
      severity: page
    annotations:
      summary: "Instance Memory Usage High"
      description: "Memory usage above 80% (current value: {{ $value }})"
   
# xwk
- name: docker
  rules:
  - alert: ms.zbx.lab - host2 - mysql
    expr: count(container_start_time_seconds{name='mysql'}) == 0
    for: 10s
    labels:
      severity: page
    annotations:
      summary: "容器停止"
      description: "mysql 容器不能访问"
  - alert: ms.zbx.lab - test - ttt
    expr: count(container_start_time_seconds{name='ttt'}) == 0
    for: 10s
    labels:
      severity: xwk
    annotations:
      summary: "容器停止"
      description: "ttt 容器不能访问"


#
# docker container
#  - alert: Container_all_cpu_usage
#    expr: (sum by(name)(rate(container_cpu_usage_seconds_total{image!=""}[5m]))*100) > 75
#    for: 5m
#    labels:
#      severity: critical
#    annotations:
#      description: 容器 {{ $labels.name }} CPU 资源利用率大于 75% , (current value is {{ $value }})
#      summary: lab CPU 负载告警
#  - alert: Container_all_memory_usage
#    expr: sort_desc(avg by(name)(irate(container_memory_usage_bytes{name!=""}[5m]))*100) > 1024*10^3*1
#    for: 10m
#    labels:
#      severity: critical
#    annotations:
#      description: 容器 {{ $labels.name }} Memory 资源利用率大于 1G , (current value is {{ $value }})
#      summary: lab Memory 负载告警
#  - alert: Container_all_network_receive_usage
#    expr: sum by (name)(irate(container_network_receive_bytes_total{container_name="POD"}[1m])) > 1024*1024*50
#    for: 10m
#    labels:
#      severity: critical
#    annotations:
#      description: 容器 {{ $labels.name }} network_receive 资源利用率大于 50M , (current value is {{ $value }})
#      summary: network_receive 负载告警
