global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s
rule_files:
  - 'rules/alertmanager-rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]
    scheme: http
    timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'file_ds'
    file_sd_configs:
    - files:
      - targets.yml
